set gaSet(sw)          "??"
set gaSet(dbrSW)       "6.7.1(0.53)"
set gaSet(swPack)      "SW3260"
set gaSet(dbrBVerSw)   "SW3485"
set gaSet(dbrBVer)     "1.11"
set gaSet(cpld)        "03"
set gaSet(DutFullName) "ETX-2I/ACR/19/64E1/SYE"
set gaSet(DutInitName) "ETX-2I.ACR.19.64E1.SYE.tcl"
set gaSet(BootCF) "c:/aa"
set gaSet(SWCF) "C:/Users/ate-j-r/Desktop/JAT_Burn_64e1_for rev D/sw-pack_2i.bin"
set gaSet(DGaspCF) "C:/AT-ETX-2i-64ET1/ConfFiles/DGasp.txt"
set gaSet(ExtClkCF) "c:/aa"
set gaSet(EthLink_UUTCF) "C:/AT-ETX-2i-64ET1/ConfFiles/FTI_dut_config_new.txt"
set gaSet(EthLink_REFCF) "C:/AT-ETX-2i-64ET1/ConfFiles/FTI_ref_config_new.txt"
set gaSet(SyncEMasterCF) "c:/aa"
set gaSet(Aux1CF) "C:/AT-ETX-2i-64ET1/ConfFiles/ETX-205_dev1.txt"
set gaSet(Aux2CF) "C:/AT-ETX-2i-64ET1/ConfFiles/ETX-205_dev2.txt"
set gaSet(licDir) "??"
